import { Appointment } from '../types';
import { addDays } from 'date-fns';

// Helper function to set time on a date
const setTime = (date: Date, hours: number, minutes: number = 0): Date => {
  const newDate = new Date(date);
  newDate.setHours(hours, minutes, 0, 0);
  return newDate;
};

// Current date reference
const today = new Date();
const tomorrow = addDays(today, 1);
const dayAfterTomorrow = addDays(today, 2);
const nextWeek = addDays(today, 7);

export const mockAppointments: Appointment[] = [
  {
    id: '1',
    patientId: 'p1',
    patientName: 'John Smith',
    patientPhoto: '/assets/patients/john-smith.jpg',
    patientAge: 45,
    patientGender: 'Male',
    startTime: setTime(today, 9, 0),
    endTime: setTime(today, 9, 30),
    duration: 30,
    purpose: 'Follow-up for diabetes management',
    status: 'confirmed',
    preparationStatus: 'Lab results received',
    notes: 'Patient reported improved glucose levels',
    type: 'follow-up',
  },
  {
    id: '2',
    patientId: 'p2',
    patientName: 'Emma Johnson',
    patientPhoto: '/assets/patients/emma-johnson.jpg',
    patientAge: 32,
    patientGender: 'Female',
    startTime: setTime(today, 10, 0),
    endTime: setTime(today, 10, 45),
    duration: 45,
    purpose: 'Annual check-up',
    status: 'pending',
    type: 'check-up',
  },
  {
    id: '3',
    patientId: 'p3',
    patientName: 'Michael Brown',
    patientPhoto: '/assets/patients/michael-brown.jpg',
    patientAge: 58,
    patientGender: 'Male',
    startTime: setTime(today, 13, 0),
    endTime: setTime(today, 14, 0),
    duration: 60,
    purpose: 'Post-surgery evaluation',
    status: 'confirmed',
    preparationStatus: 'X-ray results needed',
    type: 'follow-up',
  },
  {
    id: '4',
    patientId: 'p4',
    patientName: 'Sophia Wilson',
    patientPhoto: '/assets/patients/sophia-wilson.jpg',
    patientAge: 28,
    patientGender: 'Female',
    startTime: setTime(today, 15, 0),
    endTime: setTime(today, 15, 30),
    duration: 30,
    purpose: 'Headache consultation',
    status: 'confirmed',
    type: 'consultation',
  },
  {
    id: '5',
    patientId: 'p5',
    patientName: 'William Davis',
    patientPhoto: '/assets/patients/william-davis.jpg',
    patientAge: 62,
    patientGender: 'Male',
    startTime: setTime(tomorrow, 9, 0),
    endTime: setTime(tomorrow, 10, 0),
    duration: 60,
    purpose: 'Heart condition follow-up',
    status: 'confirmed',
    preparationStatus: 'EKG scheduled',
    type: 'follow-up',
  },
  {
    id: '6',
    patientId: 'p6',
    patientName: 'Olivia Martinez',
    patientPhoto: '/assets/patients/olivia-martinez.jpg',
    patientAge: 35,
    patientGender: 'Female',
    startTime: setTime(tomorrow, 11, 0),
    endTime: setTime(tomorrow, 11, 45),
    duration: 45,
    purpose: 'Pregnancy check-up',
    status: 'confirmed',
    type: 'check-up',
  },
  {
    id: '7',
    patientId: 'p7',
    patientName: 'James Taylor',
    patientAge: 52,
    patientGender: 'Male',
    startTime: setTime(tomorrow, 14, 0),
    endTime: setTime(tomorrow, 15, 0),
    duration: 60,
    purpose: 'Knee replacement surgery prep',
    status: 'pending',
    preparationStatus: 'Pre-op lab work pending',
    type: 'surgery',
  },
  {
    id: '8',
    patientId: 'p8',
    patientName: 'Ava Robinson',
    patientAge: 7,
    patientGender: 'Female',
    startTime: setTime(dayAfterTomorrow, 16, 0),
    endTime: setTime(dayAfterTomorrow, 16, 30),
    duration: 30,
    purpose: 'Ear infection follow-up',
    status: 'confirmed',
    type: 'follow-up',
  },
  {
    id: '9',
    patientId: 'p9',
    patientName: 'Lucas Garcia',
    patientAge: 42,
    patientGender: 'Male',
    startTime: setTime(dayAfterTomorrow, 9, 0),
    endTime: setTime(dayAfterTomorrow, 9, 30),
    duration: 30,
    purpose: 'Blood pressure check',
    status: 'confirmed',
    type: 'follow-up',
  },
  {
    id: '10',
    patientId: 'p10',
    patientName: 'Charlotte Lee',
    patientAge: 65,
    patientGender: 'Female',
    startTime: setTime(dayAfterTomorrow, 11, 0),
    endTime: setTime(dayAfterTomorrow, 11, 45),
    duration: 45,
    purpose: 'Arthritis consultation',
    status: 'confirmed',
    type: 'consultation',
  },
  // Create a conflict for demonstration
  {
    id: '11',
    patientId: 'p11',
    patientName: 'Daniel White',
    patientAge: 38,
    patientGender: 'Male',
    startTime: setTime(today, 9, 15), // Overlaps with John Smith's appointment
    endTime: setTime(today, 9, 45),
    duration: 30,
    purpose: 'Back pain consultation',
    status: 'confirmed',
    type: 'consultation',
  },
  {
    id: '12',
    patientId: 'p12',
    patientName: 'Isabella Clark',
    patientAge: 29,
    patientGender: 'Female',
    startTime: setTime(nextWeek, 10, 0),
    endTime: setTime(nextWeek, 10, 30),
    duration: 30,
    purpose: 'Follow-up for medication adjustment',
    status: 'confirmed',
    type: 'follow-up',
  },
];