export const mockPatients = [
    {
      id: 'p1',
      name: 'John Smith',
      age: 45,
      gender: 'Male' as const,
      photo: '/assets/patients/john-smith.jpg',
      phoneNumber: '(555) 123-4567',
      email: 'john.smith@example.com',
      address: '123 Main St, Anytown, USA',
      medicalHistory: 'Type 2 Diabetes, Hypertension',
      lastVisit: new Date('2025-03-10')
    },
    {
      id: 'p2',
      name: 'Emma Johnson',
      age: 32,
      gender: 'Female' as const,
      photo: '/assets/patients/emma-johnson.jpg',
      phoneNumber: '(555) 234-5678',
      email: 'emma.johnson@example.com',
      address: '456 Oak Ave, Somewhere, USA',
      medicalHistory: 'Asthma, Allergies',
      lastVisit: new Date('2025-03-05')
    },
    {
      id: 'p3',
      name: 'Michael Brown',
      age: 58,
      gender: 'Male' as const,
      photo: '/assets/patients/michael-brown.jpg',
      phoneNumber: '(555) 345-6789',
      email: 'michael.brown@example.com',
      address: '789 Pine Rd, Elsewhere, USA',
      medicalHistory: 'Post Heart Surgery, Arthritis',
      lastVisit: new Date('2025-03-15')
    },
    {
      id: 'p4',
      name: 'Sophia Wilson',
      age: 28,
      gender: 'Female' as const,
      photo: '/assets/patients/sophia-wilson.jpg',
      phoneNumber: '(555) 456-7890',
      email: 'sophia.wilson@example.com',
      address: '101 Maple Dr, Nowhere, USA',
      medicalHistory: 'Migraines, Anxiety',
      lastVisit: new Date('2025-03-18')
    },
    {
      id: 'p5',
      name: 'William Davis',
      age: 62,
      gender: 'Male' as const,
      photo: '/assets/patients/william-davis.jpg',
      phoneNumber: '(555) 567-8901',
      email: 'william.davis@example.com',
      address: '202 Cedar Ln, Anyplace, USA',
      medicalHistory: 'Heart Condition, High Cholesterol',
      lastVisit: new Date('2025-03-12')
    },
    {
      id: 'p6',
      name: 'Olivia Martinez',
      age: 35,
      gender: 'Female' as const,
      photo: '/assets/patients/olivia-martinez.jpg',
      phoneNumber: '(555) 678-9012',
      email: 'olivia.martinez@example.com',
      address: '303 Birch St, Somewhere Else, USA',
      medicalHistory: 'Pregnancy - Second Trimester',
      lastVisit: new Date('2025-03-08')
    },
    {
      id: 'p7',
      name: 'James Taylor',
      age: 52,
      gender: 'Male' as const,
      photo: '/assets/patients/james-taylor.jpg',
      phoneNumber: '(555) 789-0123',
      email: 'james.taylor@example.com',
      address: '404 Spruce Ct, Another Town, USA',
      medicalHistory: 'Knee Injury, Preparing for Surgery',
      lastVisit: new Date('2025-03-20')
    },
    {
      id: 'p8',
      name: 'Ava Robinson',
      age: 7,
      gender: 'Female' as const,
      photo: '/assets/patients/ava-robinson.jpg',
      phoneNumber: '(555) 890-1234',
      email: 'robinson.family@example.com',
      address: '505 Elm Blvd, Someplace, USA',
      medicalHistory: 'Recurring Ear Infections',
      lastVisit: new Date('2025-03-22')
    },
    {
      id: 'p9',
      name: 'Lucas Garcia',
      age: 42,
      gender: 'Male' as const,
      photo: '/assets/patients/lucas-garcia.jpg',
      phoneNumber: '(555) 901-2345',
      email: 'lucas.garcia@example.com',
      address: '606 Willow Way, Elsewhere, USA',
      medicalHistory: 'Hypertension, Sleep Apnea',
      lastVisit: new Date('2025-03-14')
    },
    {
      id: 'p10',
      name: 'Charlotte Lee',
      age: 65,
      gender: 'Female' as const,
      photo: '/assets/patients/charlotte-lee.jpg',
      phoneNumber: '(555) 012-3456',
      email: 'charlotte.lee@example.com',
      address: '707 Aspen Ave, Anystate, USA',
      medicalHistory: 'Arthritis, Osteoporosis',
      lastVisit: new Date('2025-03-17')
    },
    {
      id: 'p11',
      name: 'Daniel White',
      age: 38,
      gender: 'Male' as const,
      photo: '/assets/patients/daniel-white.jpg',
      phoneNumber: '(555) 123-4567',
      email: 'daniel.white@example.com',
      address: '808 Redwood Rd, Somewhere, USA',
      medicalHistory: 'Chronic Back Pain, Depression',
      lastVisit: new Date('2025-03-19')
    },
    {
      id: 'p12',
      name: 'Isabella Clark',
      age: 29,
      gender: 'Female' as const,
      photo: '/assets/patients/isabella-clark.jpg',
      phoneNumber: '(555) 234-5678',
      email: 'isabella.clark@example.com',
      address: '909 Sequoia Pl, Another City, USA',
      medicalHistory: 'Mild Epilepsy, Managed with Medication',
      lastVisit: new Date('2025-03-21')
    },
  ];